### ISSUE TITLE
change the name?

### ISSUE THREAD

**Issue by michaelficarra** [dherman/esprit#1]
It's hard to unambiguously speak about esprit in the context of JavaScript parsers, given the existence of [espree](https://github.com/eslint/espree) (a homophone).

**Comment by NekR** [comment]
Also, why the "kora" was the bad name?

**Comment by dherman** [comment]
@michaelficarra They live in separate ecosystems, so I don't really feel like the similarity should be too much of a problem.

@NekR Kora just felt like a fairly random choice of name for a JS parser (despite my personal love of West African music and culture!). And something about the name didn't feel like it had the same mouthfeel.
