### ISSUE TITLE
The trait bound `esprit::error::Error: std::error::Error` is not satisfied

### ISSUE THREAD

**Issue by djmally** [dherman/esprit#34]
As titled, `esprit::error::Error` doesn't impl `std::error::Error`. This makes using esprit errors cumbersome, as they cannot be embedded in other error types. Toy example:

```rust
pub enum MyError {
    Esprit(esprit::error::Error),
    Other,
}

impl error::Error for MyError {
    fn description(&self) -> &str {
        "oh no!"
    }

    fn cause(&self) -> Option<&error::Error> {
        match *self {
            MyError::Esprit(ref err) => Some(err), // Compiler error here
            MyError::Other => None,
        }
    }
}
```

**Comment by RReverser** [comment]
So my understanding is that we need to just implement `description` for such use cases? Sounds good to me, would you mind creating a PR?

**Comment by djmally** [comment]
The Error trait is defined as `pub trait Error: Debug + Display`, so we'd need to implement `Display` first and then impl `error::Error`. I have most of a PR ready, it's pretty straightforward.

**Comment by RReverser** [comment]
@djmally 

> so we'd need to implement Display first and then impl error::Error (just define description and cause)

not necessarily, I played locally and for many cases we already have simple string, so can go another way - implement `Error` first and then in `Display` just do `fmt.write_str(self.description())`.

**Comment by djmally** [comment]
@RReverser I just stubbed that out quickly to see how it would work, unfortunately it causes other problems:
```rust
error: no method named `description` found for type `&error::Error` in the current scope
  --> src/error.rs:57:26
   |
57 |         f.write_str(self.description())
   |                          ^^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
   = help: candidate #1: `use std::error::Error;`
```
The compiler's solution is not especially useful either, since `use std::error::Error` puts the trait `Error` into scope, yet there's already an `Error` enum defined in this module... Maybe there's a way to get around that, I'm not sure.

Moreover, if we want to properly implement `cause` (from the `Error` trait) for Esprit Errors, `joker::error::Error` and `easter::cover::Error` also need to have `std::error::Error` implemented, since they  cause the same problem that `esprit::error::Error` causes in my own crate. We could have `cause` return `None` regardless, but I think it's better to get the implementation right the first time.

**Comment by RReverser** [comment]
> Maybe there's a way to get around that, I'm not sure.

Indeed. What I did was insert `use std:error::Error as StdError;` at the top in which case trait is in scope, but compiler doesn't care under which name it is. After that, you can both `impl StdError for Error { ... }` and do `.description()` without hacks.

**Comment by RReverser** [comment]
Sure, feel free to implement `Error` for all the error types.

**Comment by djmally** [comment]
>What I did was insert use std:error::Error as StdError;

Totally forgot about that syntax 😄 Cool, that should be a lot easier. I'll go ahead and implement `std::errorError` for all the necessary components.

**Comment by djmally** [comment]
PR: https://github.com/dherman/esprit/pull/36
